# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz
      - run: tar -xzf sc-latest-linux.tar.gz
      - run: npm install
  test:
    docker:
      - image: circleci/node:6
    steps:
      - run: 
          command: cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --readyfile ~/sauce_is_ready
          background: true
      # Wait for tunnel to be ready
      - run: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
      - run: npm run test:selenium
  post: 
    - run: killall --wait sc  # wait for Sauce Connect to close the tunnel
