# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz
      - run: tar -xzf sc-latest-linux.tar.gz
  test:
    docker:
      - image: circleci/node:6
    steps:
      - run: yarn test
      - run: 
          command: cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --readyfile ~/sauce_is_ready
          background: true
      # Wait for tunnel to be ready
      - run: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
      - run: npm run test:selenium
  post: 
    - run: killall --wait sc  # wait for Sauce Connect to close the tunnel
